### ISSUE TITLE
Improvement: keybind to stop the autodrawer

### ISSUE THREAD

**Issue by AG89** [yoyochris924/AutoDrawer#1]
I really like this program but the only issue is that there's no keybind to stop the drawing. It gets pretty annoying when I have other windows open and the autodrawer starts to press on other areas when I try to drag the cursor to a corner.

**Comment by ChristopherBaim** [comment]
Great idea! I used the `keyboard` module to add Esc as a hotkey for a keyboard interrupt. You'll have to add the `keyboard` module if you don't have it already, but I added a `requirements.txt` now so it should be easier.

**Comment by AG89** [comment]
thanks! this really help me a lot!
