### ISSUE TITLE
Immediately closing after open 

### ISSUE THREAD

**Issue by Guilded1** [yoyochris924/AutoDrawer#3]
Title says it all, It closes immediately after opening.

**Comment by ChristopherBaim** [comment]
That would happen if you were clicking the AutoDrawer.py file to run it. If that's the case, then try to run the script from the terminal instead. There will also be requirements you need to install, which are listed in the requirements.txt file.

**Comment by Guilded1** [comment]
My guess is that it is because of an invalid python version, what version was this for?

**Comment by ChristopherBaim** [comment]
I've tested with Python 3.9. Could you provide any more details about how you're running the file?

**Comment by Guilded1** [comment]
I tried running it on cmd, the error was
import pyautogui
ModuleNotFoundError: No module named 'pyautogui'

**Comment by ChristopherBaim** [comment]
Thank you. You'll need to install the dependencies included in the requirements.txt file, which is included in the repository. You can do that with the command `pip install -r requirements.txt` from the command prompt if you're in the same directory as the requirements.txt file.

**Comment by Guilded1** [comment]
Fixed, just had to install requirements.txt.

**Comment by cutecg** [comment]
how do I do any of that? I understood what to do I have some coding experience but I do not understand how to get into the directory to run the install command. Is there any way I can get a more detailed explanation to go from downloaded files to a working program?

**Comment by ChristopherBaim** [comment]
Do you have Python installed? If not, you can find installation instructions [here](https://realpython.com/installing-python/).

When Python is installed, you'll need to use the terminal/command line to navigate to your local folder containing the [AutoDrawer.py](https://github.com/ChristopherBaim/AutoDrawer/blob/master/AutoDrawer.py) and [requirements.txt](https://github.com/ChristopherBaim/AutoDrawer/blob/master/requirements.txt) files from this repository. Then you'll use pip to install the dependencies from the `requirements.txt` file with the command: `pip install -r requirements.txt`  . Then you'll launch the `AutoDrawer.py` file from the command line.

If you have issues installing the requirements, [this resource may help you](https://packaging.python.org/en/latest/tutorials/installing-packages/).
